//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.Validation"/> </summary
    public sealed class ValidationClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public ValidationClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "Validation";
            }
        }
        
        /// <summary>
        /// Call the ValidateHash method on the Validation microservice
        /// <see cref="Beamable.Microservices.Validation.ValidateHash"/>
        /// </summary>
        public Beamable.Common.Promise<bool> ValidateHash(string walletAddress, string message, string transactionHash)
        {
            object raw_walletAddress = walletAddress;
            object raw_message = message;
            object raw_transactionHash = transactionHash;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("walletAddress", raw_walletAddress);
            serializedFields.Add("message", raw_message);
            serializedFields.Add("transactionHash", raw_transactionHash);
            return this.Request<bool>("Validation", "ValidateHash", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersValidationClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForValidationClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<ValidationClient>();
        }
        
        public static ValidationClient Validation(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<ValidationClient>();
        }
    }
}
